In [2]:
import pandas as pd
import numpy as np

In [6]:
# Task 1
s1 = pd.Series(np.random.rand(4))
s2 = pd.Series(np.random.rand(4))
s3 = pd.Series(np.random.rand(4))
s4 = pd.Series(np.random.rand(4))
df = pd.DataFrame([s1, s2, s3, s4])
df

          0         1         2         3
0  0.080684  0.531692  0.283912  0.265229
1  0.747956  0.589624  0.820279  0.322307
2  0.788244  0.330475  0.435897  0.531342
3  0.897598  0.278749  0.377947  0.474142

In [7]:
# Task 2
df.columns = ['Random Value 1', 'Random Value 2', 'Random Value 3', 'Random Value 4']
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.080684        0.531692        0.283912        0.265229
1        0.747956        0.589624        0.820279        0.322307
2        0.788244        0.330475        0.435897        0.531342
3        0.897598        0.278749        0.377947        0.474142

In [8]:
# Task 3
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.628620        0.432635        0.479509        0.398255
std          0.370722        0.151190        0.235654        0.125080
min          0.080684        0.278749        0.283912        0.265229
25%          0.581138        0.317543        0.354439        0.308037
50%          0.768100        0.431084        0.406922        0.398224
75%          0.815583        0.546175        0.531992        0.488442
max          0.897598        0.589624        0.820279        0.531342

In [14]:
# Task 4 (Column Null Values)
df.isnull().sum()

Random Value 1    0
Random Value 2    0
Random Value 3    0
Random Value 4    0
dtype: int64

In [15]:
# Task 4 (Column DataType)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      float64
 1   Random Value 2  4 non-null      float64
 2   Random Value 3  4 non-null      float64
 3   Random Value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [21]:
# Task 5 (Location Method)
df.loc[0:,'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0        0.531692        0.283912
1        0.589624        0.820279
2        0.330475        0.435897
3        0.278749        0.377947

In [20]:
# Task 5 (Index Location Method)
df.iloc[0:,1:3]

   Random Value 2  Random Value 3
0        0.531692        0.283912
1        0.589624        0.820279
2        0.330475        0.435897
3        0.278749        0.377947