In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
from sklearn.preprocessing import LabelEncoder

In [66]:
from sklearn.model_selection import train_test_split

In [99]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [67]:
df = pd.read_csv('/content/drug200.csv')
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [68]:
df['Sex'].value_counts()

M    104
F     96
Name: Sex, dtype: int64

In [69]:
df['BP'].value_counts()

HIGH      77
LOW       64
NORMAL    59
Name: BP, dtype: int64

In [70]:
df['Cholesterol'].value_counts()

HIGH      103
NORMAL     97
Name: Cholesterol, dtype: int64

In [71]:
df['Drug'].value_counts()

DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

In [72]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [73]:
l1 = LabelEncoder()
l2 = LabelEncoder()
l3 = LabelEncoder()
df['Sex'] = l1.fit_transform(df['Sex'])
df['BP'] = l2.fit_transform(df['BP'])
df['Cholesterol'] = l3.fit_transform(df['Cholesterol'])
df.head()

   Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  DrugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  DrugY

In [74]:
x = df.iloc[:,:5].values
x

array([[23.   ,  0.   ,  0.   ,  0.   , 25.355],
       [47.   ,  1.   ,  1.   ,  0.   , 13.093],
       [47.   ,  1.   ,  1.   ,  0.   , 10.114],
       [28.   ,  0.   ,  2.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  1.   ,  0.   , 18.043],
       [22.   ,  0.   ,  2.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  2.   ,  0.   , 16.275],
       [41.   ,  1.   ,  1.   ,  0.   , 11.037],
       [60.   ,  1.   ,  2.   ,  0.   , 15.171],
       [43.   ,  1.   ,  1.   ,  1.   , 19.368],
       [47.   ,  0.   ,  1.   ,  0.   , 11.767],
       [34.   ,  0.   ,  0.   ,  1.   , 19.199],
       [43.   ,  1.   ,  1.   ,  0.   , 15.376],
       [74.   ,  0.   ,  1.   ,  0.   , 20.942],
       [50.   ,  0.   ,  2.   ,  0.   , 12.703],
       [16.   ,  0.   ,  0.   ,  1.   , 15.516],
       [69.   ,  1.   ,  1.   ,  1.   , 11.455],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [23.   ,  1.   ,  1.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  0.   ,  1.   , 25.974],
       [57.   ,  1.   ,  1.   ,  1.   , 19.128],
       [63.   ,  1.   ,  2.   ,  0.   , 25.917],
       [47.   ,  1.   ,  1.   ,  1.   , 30.568],
       [48.   ,  0.   ,  1.   ,  0.   , 15.036],
       [33.   ,  0.   ,  1.   ,  0.   , 33.486],
       [28.   ,  0.   ,  0.   ,  1.   , 18.809],
       [31.   ,  1.   ,  0.   ,  0.   , 30.366],
       [49.   ,  0.   ,  2.   ,  1.   ,  9.381],
       [39.   ,  0.   ,  1.   ,  1.   , 22.697],
       [45.   ,  1.   ,  1.   ,  0.   , 17.951],
       [18.   ,  0.   ,  2.   ,  1.   ,  8.75 ],
       [74.   ,  1.   ,  0.   ,  0.   ,  9.567],
       [49.   ,  1.   ,  1.   ,  1.   , 11.014],
       [65.   ,  0.   ,  0.   ,  1.   , 31.876],
       [53.   ,  1.   ,  2.   ,  0.   , 14.133],
       [46.   ,  1.   ,  2.   ,  1.   ,  7.285],
       [32.   ,  1.   ,  0.   ,  1.   ,  9.445],
       [39.   ,  1.   ,  1.   ,  1.   , 13.938],
       [39.   ,  0.   ,  2.   ,  1.   ,  9.709],
       [15.   ,  1.   ,  2.   ,  0.   ,  9.084],
       [73.   ,  0.   ,  2.   ,  0.   , 19.221],
       [58.   ,  0.   ,  0.   ,  1.   , 14.239],
       [50.   ,  1.   ,  2.   ,  1.   , 15.79 ],
       [23.   ,  1.   ,  2.   ,  0.   , 12.26 ],
       [50.   ,  0.   ,  2.   ,  1.   , 12.295],
       [66.   ,  0.   ,  2.   ,  1.   ,  8.107],
       [37.   ,  0.   ,  0.   ,  0.   , 13.091],
       [68.   ,  1.   ,  1.   ,  0.   , 10.291],
       [23.   ,  1.   ,  2.   ,  0.   , 31.686],
       [28.   ,  0.   ,  1.   ,  0.   , 19.796],
       [58.   ,  0.   ,  0.   ,  0.   , 19.416],
       [67.   ,  1.   ,  2.   ,  1.   , 10.898],
       [62.   ,  1.   ,  1.   ,  1.   , 27.183],
       [24.   ,  0.   ,  0.   ,  1.   , 18.457],
       [68.   ,  0.   ,  0.   ,  1.   , 10.189],
       [26.   ,  0.   ,  1.   ,  0.   , 14.16 ],
       [65.   ,  1.   ,  0.   ,  1.   , 11.34 ],
       [40.   ,  1.   ,  0.   ,  0.   , 27.826],
       [60.   ,  1.   ,  2.   ,  1.   , 10.091],
       [34.   ,  1.   ,  0.   ,  0.   , 18.703],
       [38.   ,  0.   ,  1.   ,  1.   , 29.875],
       [24.   ,  1.   ,  0.   ,  1.   ,  9.475],
       [67.   ,  1.   ,  1.   ,  1.   , 20.693],
       [45.   ,  1.   ,  1.   ,  1.   ,  8.37 ],
       [60.   ,  0.   ,  0.   ,  0.   , 13.303],
       [68.   ,  0.   ,  2.   ,  1.   , 27.05 ],
       [29.   ,  1.   ,  0.   ,  0.   , 12.856],
       [17.   ,  1.   ,  2.   ,  1.   , 10.832],
       [54.   ,  1.   ,  2.   ,  0.   , 24.658],
       [18.   ,  0.   ,  0.   ,  1.   , 24.276],
       [70.   ,  1.   ,  0.   ,  0.   , 13.967],
       [28.   ,  0.   ,  2.   ,  0.   , 19.675],
       [24.   ,  0.   ,  2.   ,  0.   , 10.605],
       [41.   ,  0.   ,  2.   ,  1.   , 22.905],
       [31.   ,  1.   ,  0.   ,  1.   , 17.069],
       [26.   ,  1.   ,  1.   ,  1.   , 20.909],
       [36.   ,  0.   ,  0.   ,  0.   , 11.198],
       [26.   ,  0.   ,  0.   ,  1.   , 19.161],
       [19.   ,  0.   ,  0.   ,  0.   , 13.313],
       [32.   ,  0.   ,  1.   ,  1.   , 10.84 ],
       [60.   ,  1.   ,  0.   ,  0.   , 13.934],
       [64.   ,  1.   ,  2.   ,  0.   ,  7.761],
       [32.   ,  0.   ,  1.   ,  0.   ,  9.712],
       [38.   ,  0.   ,  0.   ,  1.   , 11.326],
       [47.   ,  0.   ,  1.   ,  0.   , 10.067],
       [59.   ,  1.   ,  0.   ,  0.   , 13.935],
       [51.   ,  0.   ,  2.   ,  0.   , 13.597],
       [69.   ,  1.   ,  1.   ,  0.   , 15.478],
       [37.   ,  0.   ,  0.   ,  1.   , 23.091],
       [50.   ,  0.   ,  2.   ,  1.   , 17.211],
       [62.   ,  1.   ,  2.   ,  0.   , 16.594],
       [41.   ,  1.   ,  0.   ,  1.   , 15.156],
       [29.   ,  0.   ,  0.   ,  0.   , 29.45 ],
       [42.   ,  0.   ,  1.   ,  1.   , 29.271],
       [56.   ,  1.   ,  1.   ,  0.   , 15.015],
       [36.   ,  1.   ,  1.   ,  1.   , 11.424],
       [58.   ,  0.   ,  1.   ,  0.   , 38.247],
       [56.   ,  0.   ,  0.   ,  0.   , 25.395],
       [20.   ,  1.   ,  0.   ,  1.   , 35.639],
       [15.   ,  0.   ,  0.   ,  1.   , 16.725],
       [31.   ,  1.   ,  0.   ,  1.   , 11.871],
       [45.   ,  0.   ,  0.   ,  0.   , 12.854],
       [28.   ,  0.   ,  1.   ,  0.   , 13.127],
       [56.   ,  1.   ,  2.   ,  0.   ,  8.966],
       [22.   ,  1.   ,  0.   ,  1.   , 28.294],
       [37.   ,  1.   ,  1.   ,  1.   ,  8.968],
       [22.   ,  1.   ,  2.   ,  0.   , 11.953],
       [42.   ,  1.   ,  1.   ,  0.   , 20.013],
       [72.   ,  1.   ,  0.   ,  1.   ,  9.677],
       [23.   ,  1.   ,  2.   ,  0.   , 16.85 ],
       [50.   ,  1.   ,  0.   ,  0.   ,  7.49 ],
       [47.   ,  0.   ,  2.   ,  1.   ,  6.683],
       [35.   ,  1.   ,  1.   ,  1.   ,  9.17 ],
       [65.   ,  0.   ,  1.   ,  1.   , 13.769],
       [20.   ,  0.   ,  2.   ,  1.   ,  9.281],
       [51.   ,  1.   ,  0.   ,  0.   , 18.295],
       [67.   ,  1.   ,  2.   ,  1.   ,  9.514],
       [40.   ,  0.   ,  2.   ,  0.   , 10.103],
       [32.   ,  0.   ,  0.   ,  1.   , 10.292],
       [61.   ,  0.   ,  0.   ,  0.   , 25.475],
       [28.   ,  1.   ,  2.   ,  0.   , 27.064],
       [15.   ,  1.   ,  0.   ,  1.   , 17.206],
       [34.   ,  1.   ,  2.   ,  0.   , 22.456],
       [36.   ,  0.   ,  2.   ,  0.   , 16.753],
       [53.   ,  0.   ,  0.   ,  1.   , 12.495],
       [19.   ,  0.   ,  0.   ,  1.   , 25.969],
       [66.   ,  1.   ,  0.   ,  0.   , 16.347],
       [35.   ,  1.   ,  2.   ,  1.   ,  7.845],
       [47.   ,  1.   ,  1.   ,  1.   , 33.542],
       [32.   ,  0.   ,  2.   ,  0.   ,  7.477],
       [70.   ,  0.   ,  2.   ,  0.   , 20.489],
       [52.   ,  1.   ,  1.   ,  1.   , 32.922],
       [49.   ,  1.   ,  1.   ,  1.   , 13.598],
       [24.   ,  1.   ,  2.   ,  0.   , 25.786],
       [42.   ,  0.   ,  0.   ,  0.   , 21.036],
       [74.   ,  1.   ,  1.   ,  1.   , 11.939],
       [55.   ,  0.   ,  0.   ,  0.   , 10.977],
       [35.   ,  0.   ,  0.   ,  0.   , 12.894],
       [51.   ,  1.   ,  0.   ,  1.   , 11.343],
       [69.   ,  0.   ,  2.   ,  0.   , 10.065],
       [49.   ,  1.   ,  0.   ,  1.   ,  6.269],
       [64.   ,  0.   ,  1.   ,  1.   , 25.741],
       [60.   ,  1.   ,  0.   ,  1.   ,  8.621],
       [74.   ,  1.   ,  0.   ,  1.   , 15.436],
       [39.   ,  1.   ,  0.   ,  0.   ,  9.664],
       [61.   ,  1.   ,  2.   ,  0.   ,  9.443],
       [37.   ,  0.   ,  1.   ,  1.   , 12.006],
       [26.   ,  0.   ,  0.   ,  1.   , 12.307],
       [61.   ,  0.   ,  1.   ,  1.   ,  7.34 ],
       [22.   ,  1.   ,  1.   ,  0.   ,  8.151],
       [49.   ,  1.   ,  0.   ,  1.   ,  8.7  ],
       [68.   ,  1.   ,  0.   ,  0.   , 11.009],
       [55.   ,  1.   ,  2.   ,  1.   ,  7.261],
       [72.   ,  0.   ,  1.   ,  1.   , 14.642],
       [37.   ,  1.   ,  1.   ,  1.   , 16.724],
       [49.   ,  1.   ,  1.   ,  0.   , 10.537],
       [31.   ,  1.   ,  0.   ,  1.   , 11.227],
       [53.   ,  1.   ,  1.   ,  0.   , 22.963],
       [59.   ,  0.   ,  1.   ,  0.   , 10.444],
       [34.   ,  0.   ,  1.   ,  1.   , 12.923],
       [30.   ,  0.   ,  2.   ,  0.   , 10.443],
       [57.   ,  0.   ,  0.   ,  1.   ,  9.945],
       [43.   ,  1.   ,  2.   ,  1.   , 12.859],
       [21.   ,  0.   ,  0.   ,  1.   , 28.632],
       [16.   ,  1.   ,  0.   ,  1.   , 19.007],
       [38.   ,  1.   ,  1.   ,  0.   , 18.295],
       [58.   ,  0.   ,  1.   ,  0.   , 26.645],
       [57.   ,  0.   ,  2.   ,  0.   , 14.216],
       [51.   ,  0.   ,  1.   ,  1.   , 23.003],
       [20.   ,  0.   ,  0.   ,  0.   , 11.262],
       [28.   ,  0.   ,  2.   ,  0.   , 12.879],
       [45.   ,  1.   ,  1.   ,  1.   , 10.017],
       [39.   ,  0.   ,  2.   ,  1.   , 17.225],
       [41.   ,  0.   ,  1.   ,  1.   , 18.739],
       [42.   ,  1.   ,  0.   ,  1.   , 12.766],
       [73.   ,  0.   ,  0.   ,  0.   , 18.348],
       [48.   ,  1.   ,  0.   ,  1.   , 10.446],
       [25.   ,  1.   ,  2.   ,  0.   , 19.011],
       [39.   ,  1.   ,  2.   ,  0.   , 15.969],
       [67.   ,  0.   ,  2.   ,  0.   , 15.891],
       [22.   ,  0.   ,  0.   ,  1.   , 22.818],
       [59.   ,  0.   ,  2.   ,  0.   , 13.884],
       [20.   ,  0.   ,  1.   ,  1.   , 11.686],
       [36.   ,  0.   ,  0.   ,  1.   , 15.49 ],
       [18.   ,  0.   ,  0.   ,  0.   , 37.188],
       [57.   ,  0.   ,  2.   ,  1.   , 25.893],
       [70.   ,  1.   ,  0.   ,  0.   ,  9.849],
       [47.   ,  1.   ,  0.   ,  0.   , 10.403],
       [65.   ,  1.   ,  0.   ,  1.   , 34.997],
       [64.   ,  1.   ,  0.   ,  1.   , 20.932],
       [58.   ,  1.   ,  0.   ,  0.   , 18.991],
       [23.   ,  1.   ,  0.   ,  0.   ,  8.011],
       [72.   ,  1.   ,  1.   ,  0.   , 16.31 ],
       [72.   ,  1.   ,  1.   ,  0.   ,  6.769],
       [46.   ,  0.   ,  0.   ,  0.   , 34.686],
       [56.   ,  0.   ,  1.   ,  0.   , 11.567],
       [16.   ,  1.   ,  1.   ,  0.   , 12.006],
       [52.   ,  1.   ,  2.   ,  0.   ,  9.894],
       [23.   ,  1.   ,  2.   ,  1.   , 14.02 ],
       [40.   ,  0.   ,  1.   ,  1.   , 11.349]])

In [75]:
y = pd.get_dummies(df.iloc[:,5:]).values
y

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [96]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 24)

In [97]:
# xtrain.space, xtest.space

In [98]:
# ytrain.space, ytest.space

In [114]:
model = Sequential()
model.add(Dense(5, activation = 'relu'))
model.add(Dense(36, activation = 'relu'))
model.add(Dense(24, activation = 'relu'))
model.add(Dense(18, activation = 'relu'))
model.add(Dense(5, activation = 'softmax'))

In [115]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [116]:
model.fit(xtrain, ytrain, batch_size = 4, epochs = 50, validation_data = (xtest, ytest))

Epoch 1/50
40/40 [==============================] - 1s 6ms/step - loss: 4.8248 - accuracy: 0.1875 - val_loss: 1.9673 - val_accuracy: 0.2000
Epoch 2/50
40/40 [==============================] - 0s 3ms/step - loss: 1.4325 - accuracy: 0.4187 - val_loss: 1.3650 - val_accuracy: 0.4750
Epoch 3/50
40/40 [==============================] - 0s 3ms/step - loss: 1.1756 - accuracy: 0.5250 - val_loss: 1.2768 - val_accuracy: 0.4750
Epoch 4/50
40/40 [==============================] - 0s 3ms/step - loss: 1.1527 - accuracy: 0.5500 - val_loss: 1.2155 - val_accuracy: 0.5000
Epoch 5/50
40/40 [==============================] - 0s 4ms/step - loss: 1.0953 - accuracy: 0.5500 - val_loss: 1.1512 - val_accuracy: 0.5000
Epoch 6/50
40/40 [==============================] - 0s 3ms/step - loss: 1.1010 - accuracy: 0.5625 - val_loss: 1.0114 - val_accuracy: 0.5250
Epoch 7/50
40/40 [==============================] - 0s 3ms/step - loss: 1.0799 - accuracy: 0.5500 - val_loss: 1.0704 - val_accuracy: 0.5500
Epoch 8/50
40/40 [==============================] - 0s 3ms/step - loss: 1.0316 - accuracy: 0.5625 - val_loss: 1.1111 - val_accuracy: 0.5250
Epoch 9/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9859 - accuracy: 0.5938 - val_loss: 1.1156 - val_accuracy: 0.5250
Epoch 10/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9931 - accuracy: 0.5875 - val_loss: 0.9344 - val_accuracy: 0.6000
Epoch 11/50
40/40 [==============================] - 0s 3ms/step - loss: 1.0399 - accuracy: 0.5500 - val_loss: 1.0793 - val_accuracy: 0.5750
Epoch 12/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9545 - accuracy: 0.6187 - val_loss: 1.1599 - val_accuracy: 0.5250
Epoch 13/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9332 - accuracy: 0.6062 - val_loss: 1.0387 - val_accuracy: 0.5500
Epoch 14/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9519 - accuracy: 0.6375 - val_loss: 0.8593 - val_accuracy: 0.6750
Epoch 15/50
40/40 [==============================] - 0s 3ms/step - loss: 0.9523 - accuracy: 0.6250 - val_loss: 1.0099 - val_accuracy: 0.5000
Epoch 16/50
40/40 [==============================] - 0s 3ms/step - loss: 0.8600 - accuracy: 0.6687 - val_loss: 0.8616 - val_accuracy: 0.6000
Epoch 17/50
40/40 [==============================] - 0s 3ms/step - loss: 0.8502 - accuracy: 0.6313 - val_loss: 0.9978 - val_accuracy: 0.6000
Epoch 18/50
40/40 [==============================] - 0s 3ms/step - loss: 0.8571 - accuracy: 0.6438 - val_loss: 0.8380 - val_accuracy: 0.6500
Epoch 19/50
40/40 [==============================] - 0s 3ms/step - loss: 0.7868 - accuracy: 0.6812 - val_loss: 0.8397 - val_accuracy: 0.6250
Epoch 20/50
40/40 [==============================] - 0s 3ms/step - loss: 0.7526 - accuracy: 0.7125 - val_loss: 0.8526 - val_accuracy: 0.6250
Epoch 21/50
40/40 [==============================] - 0s 3ms/step - loss: 0.8070 - accuracy: 0.6938 - val_loss: 0.8339 - val_accuracy: 0.6500
Epoch 22/50
40/40 [==============================] - 0s 3ms/step - loss: 0.7127 - accuracy: 0.7437 - val_loss: 0.7475 - val_accuracy: 0.7000
Epoch 23/50
40/40 [==============================] - 0s 3ms/step - loss: 0.6739 - accuracy: 0.7500 - val_loss: 0.8407 - val_accuracy: 0.6750
Epoch 24/50
40/40 [==============================] - 0s 3ms/step - loss: 0.7427 - accuracy: 0.7063 - val_loss: 0.7335 - val_accuracy: 0.7000
Epoch 25/50
40/40 [==============================] - 0s 3ms/step - loss: 0.6439 - accuracy: 0.7312 - val_loss: 0.7800 - val_accuracy: 0.6750
Epoch 26/50
40/40 [==============================] - 0s 3ms/step - loss: 0.6264 - accuracy: 0.7812 - val_loss: 0.6947 - val_accuracy: 0.7500
Epoch 27/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5853 - accuracy: 0.7937 - val_loss: 0.6284 - val_accuracy: 0.7500
Epoch 28/50
40/40 [==============================] - 0s 3ms/step - loss: 0.6289 - accuracy: 0.7437 - val_loss: 0.7105 - val_accuracy: 0.7250
Epoch 29/50
40/40 [==============================] - 0s 2ms/step - loss: 0.5975 - accuracy: 0.7500 - val_loss: 0.6292 - val_accuracy: 0.8500
Epoch 30/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5657 - accuracy: 0.8000 - val_loss: 0.7722 - val_accuracy: 0.7000
Epoch 31/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5663 - accuracy: 0.7688 - val_loss: 0.6312 - val_accuracy: 0.7750
Epoch 32/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5704 - accuracy: 0.7500 - val_loss: 0.6013 - val_accuracy: 0.8500
Epoch 33/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5375 - accuracy: 0.7812 - val_loss: 0.6515 - val_accuracy: 0.7250
Epoch 34/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5288 - accuracy: 0.7750 - val_loss: 0.7179 - val_accuracy: 0.7750
Epoch 35/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5506 - accuracy: 0.7812 - val_loss: 0.6181 - val_accuracy: 0.7750
Epoch 36/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5420 - accuracy: 0.7812 - val_loss: 0.5964 - val_accuracy: 0.7750
Epoch 37/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5009 - accuracy: 0.7750 - val_loss: 0.5853 - val_accuracy: 0.7750
Epoch 38/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4950 - accuracy: 0.8000 - val_loss: 0.7771 - val_accuracy: 0.6500
Epoch 39/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5182 - accuracy: 0.8000 - val_loss: 0.5542 - val_accuracy: 0.8500
Epoch 40/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5529 - accuracy: 0.7563 - val_loss: 0.7091 - val_accuracy: 0.6500
Epoch 41/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4713 - accuracy: 0.8188 - val_loss: 0.5721 - val_accuracy: 0.8250
Epoch 42/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5143 - accuracy: 0.8125 - val_loss: 0.7214 - val_accuracy: 0.7250
Epoch 43/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5638 - accuracy: 0.7688 - val_loss: 0.5640 - val_accuracy: 0.8000
Epoch 44/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4991 - accuracy: 0.8000 - val_loss: 0.6338 - val_accuracy: 0.7500
Epoch 45/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4588 - accuracy: 0.8250 - val_loss: 0.5960 - val_accuracy: 0.8250
Epoch 46/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4757 - accuracy: 0.8000 - val_loss: 0.5873 - val_accuracy: 0.8500
Epoch 47/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4609 - accuracy: 0.8062 - val_loss: 0.5500 - val_accuracy: 0.8250
Epoch 48/50
40/40 [==============================] - 0s 3ms/step - loss: 0.5154 - accuracy: 0.7688 - val_loss: 0.6171 - val_accuracy: 0.8000
Epoch 49/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4563 - accuracy: 0.8000 - val_loss: 0.5990 - val_accuracy: 0.7500
Epoch 50/50
40/40 [==============================] - 0s 3ms/step - loss: 0.4456 - accuracy: 0.8375 - val_loss: 0.5904 - val_accuracy: 0.8250